## name: rabbits
## author: lazyload
## license: AGPL v3
## blurb: Adaptation of the Orca theme from
## https://github.com/hundredrabbits/Themes, with additional colors from the
## various rabbits. All credits to the original authors: 100r.co.


#: The basic colors

foreground                      #FFFFFF
background                      #000000
selection_foreground            #FFFFFF
selection_background            #222222


#: Cursor colors

cursor                          #FFFFFF
cursor_text_color               #000000


#: URL underline color when hovering with mouse

url_color                       #72DEC2


#: kitty window border colors and terminal bell colors

# active_border_color             #00ff00
# inactive_border_color           #cccccc
# bell_border_color               #ff5a00
# visual_bell_color               none


#: OS Window titlebar colors

wayland_titlebar_color            #000000
macos_titlebar_color              #000000

#: Tab bar colors

# active_tab_foreground           #000
# active_tab_background           #eee
# inactive_tab_foreground         #444
# inactive_tab_background         #999
# tab_bar_background              none
# tab_bar_margin_color            none


#: Basic colors

#: black
color0 #000000
color8 #000000

#: red
color1 #DD7373
color9 #DD7373

#: green
color2  #72DEC2
color10 #72DEC2

#: yellow
color3  #FFB545
color11 #FFB545

#: blue
color4  #72DEC2
color12 #72DEC2

#: magenta
color5  #9473D7
color13 #9473D7

#: cyan
color6  #72DEC2
color14 #72DEC2

#: white
color7  #FFFFFF
color15 #FFFFFF
