return {
  { "Bilal2453/luvit-meta", enabled = false },
  { "catppuccin/nvim", enabled = false },
  { "folke/lazydev.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "linux-cultist/venv-selector.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "saecki/crates.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "MunifTanjim/nui.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
}
